name: Reusable Deployment Workflow

# This is a reusable workflow that can be called from other workflows
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'The environment to deploy to (e.g., dev, staging, production)'
      artifact-name:
        required: true
        type: string
        description: 'Name of the artifact to deploy'
      deploy-path:
        required: false
        type: string
        default: 'dist'
        description: 'Path where artifacts should be extracted'
    secrets:
      DEPLOY_TOKEN:
        required: true
        description: 'Token used for deployment authentication'
      ENV_VARS:
        required: false
        description: 'Environment-specific variables in JSON format'

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-step.outputs.deployment-url }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.deploy-path }}
      
      - name: Cache deployment dependencies
        uses: actions/cache@v3
        with:
          path: ~/.deployment-cache
          key: ${{ runner.os }}-deploy-${{ hashFiles('**/deployment-deps.lock') }}
          restore-keys: |
            ${{ runner.os }}-deploy-
      
      - name: Setup deployment tools
        run: |
          echo "Installing deployment tools..."
          # Add commands to install deployment tools based on environment
          if [[ "${{ inputs.environment }}" == "production" ]]; then
            echo "Setting up production deployment tools"
          else
            echo "Setting up non-production deployment tools"
          fi
      
      - name: Run pre-deployment checks
        run: |
          echo "Running pre-deployment validation..."
          # Add commands for pre-deployment validation
          # Example: Check if all required files exist
          if [ ! -d "${{ inputs.deploy-path }}" ]; then
            echo "Error: Deployment directory not found!"
            exit 1
          fi
      
      - name: Deploy to environment
        id: deploy-step
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
          # Add your deployment commands here based on the environment
          # Example for different environments:
          if [[ "${{ inputs.environment }}" == "production" ]]; then
            echo "Running production deployment"
            # Production-specific deployment commands
            echo "::set-output name=deployment-url::https://www.example.com"
          elif [[ "${{ inputs.environment }}" == "staging" ]]; then
            echo "Running staging deployment"
            # Staging-specific deployment commands
            echo "::set-output name=deployment-url::https://staging.example.com"
          else
            echo "Running development deployment"
            # Development-specific deployment commands
            echo "::set-output name=deployment-url::https://dev.example.com"
          fi
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          ENVIRONMENT_VARS: ${{ secrets.ENV_VARS }}
      
      - name: Set deployment status
        id: status
        run: |
          if [[ "${{ steps.verification.outcome }}" == "success" || "${{ inputs.validate-deployment }}" != "true" ]]; then
            echo "result=success" >> $GITHUB_OUTPUT
          else
            echo "result=failure" >> $GITHUB_OUTPUT
          fi
      
      - name: Generate deployment report
        run: |
          echo "# Deployment Report" > deployment-report.md
          echo "## Environment: ${{ inputs.environment }}" >> deployment-report.md
          echo "- Deployment URL: ${{ steps.deploy-step.outputs.deployment-url }}" >> deployment-report.md
          echo "- Status: ${{ steps.status.outputs.result }}" >> deployment-report.md
          echo "- Duration: ${{ steps.deploy-step.outputs.deployment-duration }} seconds" >> deployment-report.md
          echo "- Timestamp: $(date)" >> deployment-report.md
          
          if [[ "${{ steps.status.outputs.result }}" == "success" ]]; then
            echo "- Verification: Passed" >> deployment-report.md
          else
            echo "- Verification: Failed" >> deployment-report.md
            echo "  Please check the logs for more details." >> deployment-report.md
          fi
      
      - name: Upload deployment report
        uses: actions/upload-artifact@v3
        with:
          name: deployment-report-${{ inputs.environment }}
          path: deployment-report.md
          retention-days: 7
      
      - name: Send deployment notification
        if: always() && secrets.NOTIFICATION_TOKEN != ''
        uses: ./.github/actions/notify
        with:
          status: ${{ steps.status.outputs.result }}
          message: "Deployment to ${{ inputs.environment }} ${{ steps.status.outputs.result == 'success' && 'completed successfully' || 'failed' }}"
          environment: ${{ inputs.environment }}
          url: ${{ steps.deploy-step.outputs.deployment-url }}
        env:
          NOTIFICATION_TOKEN: ${{ secrets.NOTIFICATION_TOKEN }}
      
      - name: Notify deployment status
        if: always()
        run: |
          DEPLOY_STATUS="${{ job.status }}"
          echo "Deployment to ${{ inputs.environment }} status: $DEPLOY_STATUS"
          # Add notification commands (e.g., Slack, email)
          # This step runs even if previous steps fail